### ISSUE TITLE
Forked the project to MTPHP (PHP version of Managethis).

### ISSUE THREAD

**Issue by mescon** [Tenzinn3/Managethis#10]
Renamed to MTPHP (Managethis PHP) to signify the difference and minimize
confusion for users.

I opted to do this outside of Managethis which is already good for novice
users that might not want to fiddle with PHP and the (probable) over-engineering I'm gonna do on my fork.

So far the difference is:
- Added logic for the generation of menu items and iframes.
- Moved configuration to a separate config-file that will not be
  overwritten if you update from my repository.
- Added ability to enable/disable menu items with a single flag.

To come:
~~\- Dynamically generated landing-pages without code-reuse (don't want a bunch of HTML-files for each service added, where the user has to configure index.html AND a separate landing-page).~~ DONE
- Password protection of MTPHP

You're free to pull stuff that I do and add to this repo if you want to.
The fork is here: https://github.com/mescon/MTPHP

Will add more functionality as I find the time and as long as it's fun.

If I do something that I think is good that doesn't involve PHP or any server-side scripting I'll send you a pull request just to continue supporting Managethis.

Cheers!

**Comment by lxcalghost** [comment]
Great work again. I'll probably pull over what you have since I think it's a lot better idea what you're doing with the config files and also just PHP in general is going to be easier imo.

**Comment by mescon** [comment]
Absolutely - I just wanted somewhere to be able to push the changes I do directly.

If you do intend to go the PHP route yourself, might I suggest you duplicate this repo for the people that do not want/can not run PHP?

**Comment by lxcalghost** [comment]
Yup gonna leave it up and | linked to your page incase anyone comes searching.

**Comment by mescon** [comment]
Thanks mate!

**Comment by mescon** [comment]
FYI - I changed the name again, from MTPHP to Muximux - MTPHP was way to convoluted :-)
I'd be thankful if you updated your README.md to link to that instead!

Cheers!

**Comment by lxcalghost** [comment]
Yup, all done :-)
