### ISSUE TITLE
PlexPy tab doesn't work

### ISSUE THREAD

**Issue by clrung** [Tenzinn3/Managethis#14]
Hello,
I'm not sure if this is just me, but after a recent update, my PlexPy tab doesn't load anymore.

The only file I changed was config.json, which contains the following entry for PlexPy:

```
{
     "name": "plexpy",
     "icons": {
          "nav": "fa fa-server fa-lg",
          "landingpage": "fa fa-server fa-3x"
     },
     "url": "removed url"
}
```

All of my other tabs (grafana, couchpotato, plexrequests) work fine.  These also have similar addresses (just a subdomain), so I'm not sure why Managethis gets hung up on PlexPy :/  Yes, going to "removed url" works fine.

I'm not very well versed in web development, but please let me know if there are any logs from my browser that I can provide.

Thank you!

**Comment by lxcalghost** [comment]
I removed your URLs, probably not the best idea. Also can't recreate this, I'll try look into it on the weekend. What is the error that you are getting (if any)?

**Comment by clrung** [comment]
Thanks for removing the URLs.  I'm not getting any errors and have tested on both Safari and Chrome.  When I click on the Launch button, I get the authentication wall from PlexPy, but after I sign in, nothing is shown.

**Comment by torrabsolute** [comment]
clrung, I'm having the same issue. The authentication for PlexpY comes up, but nothing shows up. Did you end up resolving this?

**Comment by clrung** [comment]
Hi torrabsolute,
Unfortunately, no, I haven't resolved this issue.  Authentication comes up, but I still just see the landing page (with the Launch button).

**Comment by lxcalghost** [comment]
As with Muximux 

"If you are serving Muximux from a HTTPS-enabled webserver (i.ehttps://myserver.com/muximux), all of your services must also be secured via HTTPS. Any URL that does not start with https:// (such as http://myserver.com:5050) will be blocked by your web-browser"

The only known workaround is for Chrome, Opera and Chromium-based webbrowsers.
Install the plugin "Ignore X-Frame headers" which disables the blocking of non-secure content.
