### ISSUE TITLE
Css + JS Issues

### ISSUE THREAD

**Issue by kaishichan** [Tenzinn3/Managethis#4]
hey!

i'm having trouble with the css and js loading for the webroot not sure what i need to add to my locations block

**Comment by kaishichan** [comment]
tracked down the issue to "Resource interpreted as Stylesheet but transferred with MIME type text/plain:"

still looking for solution

**Comment by lxcalghost** [comment]
Seems like a server side issue to me, I'm not doing anything special in my setup. What web server are you running?

**Comment by mescon** [comment]
This issue should probably be closed.
@kaishichan you need to have this on a webserver with correct MIME-types. If you are using nginx, you don't need to put a special Location-block for this.
