### ISSUE TITLE
Suggestion for more glyphicons

### ISSUE THREAD

**Issue by dhowdy** [Tenzinn3/Managethis#7]
I've got a suggestion to use more glyphicions:

If you add:

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> <!--FontAwesome-->`

To the head section then you can add things like:

`class="fa fa-television"`

and whatnot for users that use SickRage.  

Not at all a problem, just a suggestion that's not worth a merge request.  Thanks for the app!

**Comment by lxcalghost** [comment]
Added
