### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by ghost** [Tenzinn3/Managethis#8]
I am running a Windows 8.1 box and have installed all the pip requirements to get this working, but when I run it with the -w flag for web monitoring, it just sits there loading never going past the splash screen. 

Let me know if you need anything else from me.

**Comment by lxcalghost** [comment]
What exactly do you mean? Are you talking about Glances? If so you are probably in the wrong place.

**Comment by ghost** [comment]
Damn! I had one job! My bad! I had multiple tabs open!
