### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by brianbuquoi** [Tenzinn3/Managethis#9]
Every time I open this page and let it sit, I will get high CPU usage and Chrome Helper will go nuts and use 100% of CPU.

Closing this screen, CPU stabilizes.

**Comment by mescon** [comment]
That is because all the applications you have linked to are all opened at the same time.
Sonarr, CouchPotato and RuTorrent especially are very JavaScript heavy which causes high usage.
Have you downloaded the latest version with the landing-pages? If so, the CPU usage should be very low.

**Comment by brianbuquoi** [comment]
I click out of them so the landing pages are active - yet still see the
high CPU usage.

**Comment by lxcalghost** [comment]
As @mescon said above its most likely a JS thing.
